name: Daily Advisor Ingestion

on:
  schedule:
    - cron: '30 4 * * *'  # Daily at 4:30am UTC
  workflow_dispatch:

jobs:
  run-advisor-ingestion:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: 📅 Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Run Advisor ingestion
        run: |
          python ingest/fetch_and_parse_advisor_xml.py

      - name: 📢 Notify Slack
        if: always()
        run: |
          STATUS="${{ job.status }}"
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"🔮 *Advisor Ingestion* completed with status: *${STATUS}*\"}" \
            $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
