name: Populate Advisor ADVs

on:
  schedule:
    - cron: '0 3 * * 0'  # Every Sunday at 3 AM UTC
  workflow_dispatch:     # Allow manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
  - name: Checkout repo
    uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install tqdm  # Force install tqdm to guarantee it's there

  - name: Run advisor ADV population script
    run: python ingest/populate_advisor_advs.py
