name: Populate Advisor ADVs

on:
  workflow_dispatch:    # Manual trigger
  schedule:
    - cron: '0 4 * * 0'  # Every Sunday at 4 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-2
      S3_BUCKET_NAME: trustgap-adv-pdfs

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install boto3 python-dotenv tqdm requests supabase

      - name: Run advisor ADV population script
        run: python -m ingest.populate_advisor_advs

