name: Run DRP Scoring Weekly

on:
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2am UTC
  workflow_dispatch:     # Manual trigger

jobs:
  run-scorer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DRP Scoring Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python scoring/drp_severity_scoring.py
